name = "AdaptiveDensityApproximationRecipes"
uuid = "36c19c45-0400-424e-9d0d-5bf8b8cd730c"
authors = ["Dominik Tschimmel <dominik.tschimmel.contact@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
